[build]
command = "./build-demo.sh"
publish = "output"

[build.environment]
BUILD_MODE = "demo"

[context.demo1.environment]
DEMO_NAME = "Demo 1"

[context.demo2.environment]
DEMO_NAME = "Demo 2"

[context.demo3.environment]
DEMO_NAME = "Demo 3"

[[redirects]]
from = "/*"
to = "/404-not-found/"
status = 404
