name: Deploy to Demo

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

# jobs:
#   build:
#     runs-on: ubuntu-latest
#
#     steps:

# DEPLOY_NAME = "Pull Request"
# BUILD_MODE = "demo"
