name: Deploy to PR Preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

env:
  PR_PREVIEW_SUBDOMAIN: pr-${{github.event.pull_request.number}}-preview

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Pull latest from submodules
        run: git submodule foreach git pull origin stable
          # This doesn't update the submodule to the latest commit on the origin; therefore, you should manually do this on a semi-regular basis.

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: ./install-production.sh

      - name: Build site
        env:
          BUILD_MODE: demo
          DEPLOY_NAME: Pull Request
        run: ./build-pr-preview.sh

      - name: "Comment on PR: Preview is building"
        id: comment-preview-building
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: |
            ## Preview is building ...

            | <!-- --> | <!-- --> |
            | --- | --- |
            | **Deploy log:** | [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) |

      - name: Deploy site
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: 'output'
          DEST_DIR: $PR_PREVIEW_SUBDOMAIN

      - name: "Update Comment on PR: Preview is ready"
        id: comment-preview-ready
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{github.event.pull_request.number}}
          comment-id: ${{ steps.comment-preview-building.outputs.comment-id }}
          body: |
            ## Preview is ready

            | <!-- --> | <!-- --> |
            | --- | --- |
            | **Preview site:** | [$PR_PREVIEW_SUBDOMAIN.knowledge.dea.ga.gov.au](https://$PR_PREVIEW_SUBDOMAIN.knowledge.dea.ga.gov.au/) |
            | **Deploy log:** | [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) |
            
