name: Publish

on:
  workflow_dispatch:
# Allow builds being triggered from the dea-notebooks repo
  repository_dispatch:
    types: [ republish-docs ]
# Build on pushes to the master branch
  push:
    branches:
      - master
# Build on pull requests TO the master branch
  pull_request:
    branches:
      - master

permissions:
  id-token: write   # This is required for requesting the JWT used by OIDC Authentication

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    name: Publish Docs
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install pandoc
      - name: Fetch notebooks
        run: |
          git clone --depth 1 https://github.com/GeoscienceAustralia/dea-notebooks notebooks
          cd notebooks && git checkout -b stable
      - name: Build docs
        run: |
          make html

      - name: Configure AWS credentials via OIDC
        if: ${{ github.event_name != 'pull_request' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::538673716275:role/github-actions-dea-docs
          aws-region: ap-southeast-2

      - name: Publish
        if: ${{ github.event_name != 'pull_request' }}
        env:
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        run: ./.deployment/deploy.sh
