name: Publish

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ republish-docs ]
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    name: Publish Docs
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get install pandoc
      - name: Fetch notebooks
        run: |
          git clone --depth 1 https://github.com/GeoscienceAustralia/dea-notebooks.git notebooks
          cd notebooks && git checkout -b docs_testing
      - name: Build docs
        run: |
          make html
      - name: Publish
        if: ${{ github.event_name != 'pull_request' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        run: ./.deployment/deploy.sh
